from pathlib import Path
from html import escape as e
import json
import re
root=Path(__file__).parent
old=(root/'dist/index.html').read_text()
head=old.split('<body>')[0].replace('Project Proof for Construction &amp; Trades','Project Stories · Central Ohio')
config_text=(root/'dist/content.js').read_text().split('window.PILLAR_CONTENT = ',1)[1].strip().removesuffix(';')
media_config=json.loads(config_text)
reel=media_config.get('reel',{})
origin='https://pillarandframe.com'
head=re.sub(r'<script id="hero-video-schema".*?</script>', '', head, flags=re.S)
head=re.sub(r'<link id="hero-poster-preload"[^>]*>', '', head)
def abs_url(u):return u if u.startswith('http') else origin+u
if reel.get('src') and reel.get('kind') in ('video','embed'):
 schema={'@context':'https://schema.org','@type':'VideoObject','name':reel['title'],'description':reel['description'],'thumbnailUrl':[abs_url(reel['poster'])],'duration':reel['duration']}
 if reel['kind']=='video': schema['contentUrl']=abs_url(reel['src'])
 else:
  schema['embedUrl']=reel['src']
  if reel.get('hls'): schema['contentUrl']=reel['hls']
 head=head.replace('</head>','<link id="hero-poster-preload" rel="preload" as="image" href="'+e(reel['poster'],quote=True)+'"><script id="hero-video-schema" type="application/ld+json">'+json.dumps(schema)+'</script></head>')
def p(s):return '<p>'+s+'</p>'
def heading(k,t):return '<div class="section-heading"><p class="eyebrow">'+k+'</p><h2>'+t+'</h2></div>'
def cta(label='Book a 15-minute call'):return '<a class="button booking" href="#booking">'+label+' <span aria-hidden="true">↗</span></a>'
def ul(items):return '<ul>'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'
def slot(key,title):
 if key=='reel' and reel.get('kind')=='embed' and reel.get('src'):
  return '<div class="media" data-media="reel"><iframe src="'+e(reel['src'],quote=True)+'" title="'+e(reel['title'],quote=True)+'" width="960" height="540" allow="fullscreen; picture-in-picture; encrypted-media" allowfullscreen loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>'
 if key=='reel' and reel.get('kind')=='video' and reel.get('src'):
  return '<div class="media" data-media="reel"><video controls playsinline preload="none" width="960" height="540" poster="'+e(reel['poster'],quote=True)+'" src="'+e(reel['src'],quote=True)+'" aria-label="'+e(reel['title'],quote=True)+'">Your browser does not support video playback.</video></div>'
 return '<div class="media" data-media="'+key+'"><div class="media-empty"><span class="frame-icon" aria-hidden="true">▷</span><strong>'+title+'</strong><span>Content placeholder · Video coming soon</span></div></div>'

h=[head,'<body><a class="skip" href="#main">Skip to content</a><div class="dark-top"><header class="wrap"><a class="brand" href="#main">pillar<span class="amp">&amp;</span>frame.</a><span class="location">Central Ohio</span><nav aria-label="Main navigation"><a href="#results">Project stories</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a>'+cta()+'</nav></header></div><main id="main">']
h+=['<div class="dark-top"><section class="hero wrap"><p class="eyebrow pill">PROJECT STORIES FOR COMMERCIAL CONTRACTORS AND TRADES</p><h1>Your work. Your story.<br><span>Your proof.</span></h1><p class="hero-sub"><strong>You build things that matter. We make sure people see it.</strong></p><p class="hero-copy">We turn your real projects into proof that closes deals faster, keeps stakeholders confident, and attracts the best tradespeople.</p><ul class="hero-benefits">'+''.join('<li>'+x+'</li>' for x in ['Win the bids you should be winning','Shorten the gap between quote and signature','Keep owners and lenders current without another meeting','Bring good people to you instead of chasing them'])+'</ul><div class="cta-row">'+cta()+'<a class="secondary" href="#reel">See a Project Story <span aria-hidden="true">↓</span></a></div><p class="local-promise">Local crews. <strong>No travel costs. Ever.</strong></p></section><section class="wrap reel" id="reel" aria-label="Project story reel">'+slot('reel','Pillar & Frame · Project reel')+'</section><div class="reel-caption wrap"><span>POWERFIELD ENERGY OVERVIEW</span><span>2 MIN 35 SEC</span></div></div>']
h+=['<section class="section wrap sameness" id="why"><div><p class="eyebrow">THE SAMENESS PROBLEM</p><h2>Quality. Reliable.<br>We go the extra mile.</h2></div><div>'+p('Your customers have heard it all before. Every contractor says it, so none of it lands, and good companies end up sounding like the ones cutting corners.')+p("The difference is out on your projects. It is in the call your PM made when the drawings were wrong. The problem you found before it became the owner's problem. The work you stood behind after the invoice was paid.")+p('We bring that into focus, and put it where it does the work.')+'</div></section>']
problems=[('Nothing to show',"You have finished a dozen projects and the only record is photos on a superintendent's phone."),('Deals stall after the quote','Your estimator sends the number and then waits. There is nothing to send on Thursday that is not a nudge.'),('Stakeholders in the dark','The owner is in another city reading a written report. He asks the same three questions every month.'),('Crews you cannot fill','You are short on every job and your careers page has a photo on it you bought from a website.')]
h+=['<section class="section soft"><div class="wrap">'+heading('SOUND FAMILIAR?','Common problems we see')+'<div class="four-grid">'+''.join('<article class="card"><span class="card-index">0'+str(i+1)+'</span><h3>'+t+'</h3>'+p(d)+'</article>' for i,(t,d) in enumerate(problems))+'</div></div></section>']
process=[('A half day on site.','We work around the job. Your crew keeps working. We bring cameras, insurance certificates, PPE and releases.'),('Access and permissions, sorted first.','Whatever the site requires, we handle before anyone shows up. You chase nothing.'),('Then we do the rest.','Interview, edit, write, build the page. You approve once, in one place, in one pass.')]
h+=['<section class="section wrap" id="process">'+heading('BUILT AROUND YOUR JOB','A half day. We handle the rest.')+'<p class="section-intro">You are running a job, not a production. The process is built to take as little from you as possible.</p><div class="process-grid">'+''.join('<article><span>0'+str(i+1)+'</span><h3>'+t+'</h3>'+p(d)+'</article>' for i,(t,d) in enumerate(process))+'</div><p class="guarantee">Fourteen days later it is live. <strong>If it is late, you do not pay.</strong></p></section>']
usecases=[('sales','SALES','Closes deals faster','The committee stops taking your word for it and watches someone who already hired you.',['The project story goes in every pre-qual package','Your estimator sends the page on Thursday instead of a nudge','One link answers the question a proposal cannot']),('stakeholders','OWNERS, LENDERS, BOARDS','Keeps stakeholders confident','The people funding the work see it, in their own time, without another meeting.',['A record of what was built and how it went','One page they can forward instead of forwarding a report','Current, dated, and theirs to share internally']),('hiring','HIRING','Attracts the best tradespeople','Your people, by name, on the work they did, beats a job board every time.',['The story shows real crews doing real work','The social cut runs on hiring posts','The page sits on the careers page and does the convincing'])]
h+=['<section class="section results" id="results"><div class="wrap">'+heading('WHAT IT DOES','Three deliverables.<br>Three jobs they do.')]
for key,label,title,desc,items in usecases:
 h+=['<article class="usecase"><div class="usecase-copy"><div><p class="eyebrow">'+label+'</p><h3>'+title+'</h3>'+p(desc)+'</div>'+ul(items)+'</div><div class="sample-grid">'+''.join('<div class="sample">'+slot(key+'-'+str(i),label.title()+' · Sample '+str(i))+'<p class="sample-caption">Project title · Client name</p></div>' for i in range(1,4))+'</div></article>']
h+=['</div></section>']
gets=[('The project story.','Two to three minutes. The job start to finish, told by the people who did it and the client it was built for. Pre-quals, presentations, the trade show booth, the homepage.'),('The social cut.','Thirty seconds from the same story. Captioned, vertical, ready to post.'),('The page.','A written case study at a link that is yours. The project, the problem, what you did, what the client said. Send it, embed it, attach it to a proposal.')]
h+=['<section class="section wrap">'+heading('WHAT YOU GET','One job, three pieces, one link.')+'<div class="three-grid">'+''.join('<article class="card"><p class="eyebrow">0'+str(i+1)+'</p><h3>'+t+'</h3>'+p(d)+'</article>' for i,(t,d) in enumerate(gets))+'</div><p class="section-intro bottom-intro">That is the unit. One job, three pieces, one link.</p></section>']
h+=['<section class="section compound"><div class="wrap sameness"><div><p class="eyebrow">IT COMPOUNDS</p><h2>One link is useful.<br><span>Four is a library.</span></h2></div><div>'+p('Do this once a quarter and by the end of the year every bid has a comparable project attached, every open role has real crews behind it, and every stakeholder has something current to look at.')+p('Nobody is digging through a folder of phone photos, because there is no reason to.')+'</div></div></section>']
h+=['<section class="section wrap deadline">'+heading('THE DEADLINE','A finished building is just a building.')+p('The proof is the work, and the work only exists while it is happening. Once the site demobilizes there is no version of this that can be recovered, at any price, by anyone.')+p('If there is a job running right now that you would want a committee to see, that is the one.')+'</section>']
h+=['<section class="section soft"><div class="wrap">'+heading('CLIENTS','In their words.')+'<div class="three-grid">'+''.join('<article class="card quote-slot" data-quote="'+str(i)+'"><span class="eyebrow">CLIENT QUOTE PLACEHOLDER</span><p class="quote-text">Client quote to be added.</p><p class="quote-person">Name · Title · Company</p></article>' for i in range(1,4))+'</div></div></section>']
h+=['<section class="section wrap" id="pricing">'+heading('PRICING','Three packages.<br>One half day on site.')+'<p class="section-intro">Pick what you need from the project. Same capture, same fourteen days, same guarantee.</p><div class="pricing-grid">']
features=['Project story, 2–3 min','Written case study page','Social cut, 30s','Quote answers, 4 × 45s','Crew piece, 60s']
for name,price,desc,count in [('Story','$4,500','For contractors who need one strong asset for the website and the pre-qual package.',2),('Story + Social','$5,500','Adds the cut your marketing person can post and your recruiter can run behind a job ad.',3),('Full','$7,500','Everything the half day can produce. The assets your estimators send and your recruiter uses, out of the same footage.',5)]:
 h+=['<article class="price-card'+(' featured' if count==5 else '')+'"><h3>'+name+'</h3><p class="price">'+price+'</p>'+p(desc)+'<ul class="feature-list">'+''.join('<li'+(' class="excluded"' if j>=count else '')+'>'+f+'<span aria-label="'+('Included' if j<count else 'Not included')+'">'+('✓' if j<count else '—')+'</span></li>' for j,f in enumerate(features))+'</ul>'+cta('Book an intro call')+'</article>']
h+=['</div><div class="included"><h3>Included in every package</h3>'+ul(['Local crews. No travel costs, in every package.','Site access, permissions and releases handled before the shoot','A half day on site, working around your job','Interview direction so nobody has to perform','Stills from the day, culled and colour corrected','Your organized raw footage','One revision round','Fourteen day delivery, guaranteed'])+'</div><div class="pricing-details"><div><h3>Capture options</h3>'+p('<strong>Half day on site.</strong> One project, one client interview, one crew interview, b-roll. The standard.')+p('<strong>Full day.</strong> Two projects, or one project with more coverage and more people on camera. Add $1,800.')+p('<strong>Multi-project day.</strong> Three sites in one day, same market, shorter coverage on each. Ask.')+'</div><div><h3>Add-ons</h3><table><caption class="sr-only">Optional deliverables and pricing</caption><thead><tr><th scope="col">Add-on</th><th scope="col">Price</th></tr></thead><tbody>'+''.join('<tr><td>'+a+'</td><td>'+b+'</td></tr>' for a,b in [('Extra quote answer video','$350 each'),('Additional social cut','Ask'),('Crew spotlight graphics, set of 6','$600'),('Silent captioned loop for trade show booths','$600'),('Additional person on camera','$450')])+'</tbody></table></div></div><div class="annual">'+p('<strong>Most clients do one a quarter.</strong> Four projects a year on an annual agreement is $6,500 per project at the Full package. By the end of the year every bid has a comparable project attached to it.')+p('<strong>Three projects a month.</strong> That is the capacity, not a tactic.')+'</div></section>']
terms=[('Fourteen days or you do not pay.','Every deliverable, in your hands, fourteen days after we leave the site. A day late and the project is free and you keep everything.'),('We work around your job.','A half day on site, on your schedule, without slowing the work down.'),('If the footage is not right, we come back on our dime.','Our crews are local, so there are never travel costs—not for the shoot, and not if we need to come back.')]
h+=['<section class="section soft"><div class="wrap">'+heading('TERMS','The things we guarantee.')+'<div class="three-grid">'+''.join('<article><h3>'+a+'</h3>'+p(b)+'</article>' for a,b in terms)+'</div><p class="terms-note">We do not guarantee you win the bid. Nobody honest can. We guarantee the proof exists, it arrives on time, and getting it does not cost you a day of production.</p></div></section>']
faqs=[('Why is the price the same for every client?','Because the deliverables are. Custom scopes are why other vendors take three weeks to send you a proposal.'),('Can I upgrade after the shoot?','Yes. We capture everything on the day regardless of package. Add the social cut or the quote answers within thirty days at the difference in price.'),('What if the project is confidential?','Then it runs work for hire. Delivered into your systems, named recipients, never shown publicly. Same price.'),('How long from the call to the page being live?','About three weeks. A week to sort access and schedule, a half day on site, fourteen days to deliver.'),('What do you need from my client?','Twenty minutes on camera and a release. We handle the ask if you would rather we did.'),('What if the weather turns?','We reschedule at no charge and the fourteen day clock starts from the new date.'),('Do we own the footage?','Yes. Your organized raw archive is included in every package.')]
h+=['<section class="section wrap faq" id="faq">'+heading('PRICING FAQ','A few things worth knowing.')+''.join('<details><summary>'+a+'</summary>'+p(b)+'</details>' for a,b in faqs)+'</section><section class="closing"><div class="wrap"><h2>The hard part<br>is already done.</h2>'+p('You built it. You solved the problems on site. The only thing missing is proof that it happened.')+cta()+p('Tell us what you are building right now. We will tell you straight whether this is worth doing.')+'</div></section></main><footer class="wrap"><a class="brand" href="#main">pillar<span class="amp">&amp;</span>frame.</a><p>Pillar &amp; Frame · Central Ohio · <a href="mailto:doyle@pillarandframe.com">doyle@pillarandframe.com</a> · <a href="tel:+13803240535">+1 380-324-0535</a></p><p class="legal-links"><a href="/privacy">Privacy policy</a> · <a href="/terms">Terms of service</a></p><a href="#main">Back to top ↑</a></footer><dialog id="booking" aria-labelledby="booking-title"><form method="dialog"><button class="close-dialog" aria-label="Close">×</button></form><p class="eyebrow">PILLAR &amp; FRAME · CENTRAL OHIO</p><h2 id="booking-title">Let’s talk about your project.</h2><p>Online booking is coming soon. Please check back for the 15-minute call link.</p><form method="dialog"><button class="button">Got it</button></form></dialog><script src="/content.js"></script><script src="/media.js"></script></body></html>']
(root/'dist/index.html').write_text('\n'.join(h))
if not (root/'dist/content.js').exists():
 config={'bookingUrl':'','reel':{'kind':'video','src':'','poster':'','title':'Pillar & Frame · Project reel','captions':''},'samples':{key+'-'+str(i):{'kind':'video','src':'','poster':'','title':label.title()+' · Sample '+str(i),'caption':'Project title · Client name','captions':''} for key,label,*_ in usecases for i in range(1,4)},'quotes':[{'quote':'','name':'','title':'','company':''} for _ in range(3)]}
 (root/'dist/content.js').write_text('// Replace empty strings with approved content. See CONTENT.md.\nwindow.PILLAR_CONTENT = '+json.dumps(config,indent=2)+';\n')
